name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Build the application
      - name: Build Pokedex App
        run: npx nx build apps/pokedex --skip-nx-cache

      # Run Jest unit tests
      - name: Run Jest Unit Tests
        run: npx nx test apps/pokedex --skip-nx-cache

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright E2E tests
      - name: Run Playwright E2E Tests
        run: npx playwright test --config=apps/pokedex-e2e/playwright.config.ts
